### ISSUE TITLE
Issues with extracting the pretrained pytorch model

### ISSUE THREAD

**Issue by debasmitdas** [jiecaoyu/pytorch_imagenet#2]
I had issues with extracting the pytorch alexnet model. Can you check and see whether its working ?
https://drive.google.com/uc?id=0B-7I62GOSnZ8NzVxZndDU2dYcHM&export=download

**Comment by SummerHuiZhang** [comment]
Me too. May I ask have you solved it? I cannot neither extract the alexnet.pth.tar nor import model_list
